# import requests

# # Define the list of URLs
# urls = [
#     "https://cloud.truestreamz.com",
#     "https://default.truestreamz.com",
#     "https://eu.truestreamz.com",
#     "https://ca.truestreamz.com",
#     "https://in.truestreamz.com",
#     "https://sf.truestreamz.com",
#     "https://np.truestreamz.com",
#     "https://dvr.truestreamz.com",
#     "https://momo.truestreamz.com",
#     "https://mnmott.truestreamz.com",
#     "https://nepaltv.truestreamz.com",
#     "https://petmarketing.truestreamz.com",
#     "https://devbroadcasters.truestreamz.com",
#     "https://mnmstg.truestreamz.com",
#     "https://nspdev.truestreamz.com",
#     "https://nspresume.truestreamz.com",
#     "https://deviptv.truestreamz.com",
#     "https://devmovies.truestreamz.com",
#     "https://devmicromovies.truestreamz.com",
#     "https://devtvshows.truestreamz.com",
#     "https://devepg.truestreamz.com",
#     "https://wodiptv.truestreamz.com",
#     "https://wodmovies.truestreamz.com",
#     "https://wodmicromovies.truestreamz.com",
#     "https://wodmwstb.truestreamz.com",
#     "https://jobterrace.truestreamz.com",
#     "https://nspweb.truestreamz.com",
#     "https://tms.truestreamz.com",
#     "https://devmwstb.truestreamz.com",
#     "https://wodtvshows.truestreamz.com",
#     "https://demoiptv.truestreamz.com",
#     "https://demomovies.truestreamz.com",
#     "https://demomicromovies.truestreamz.com",
#     "https://demotvshows.truestreamz.com",
#     "https://demomwstb.truestreamz.com",
#     "https://demohotelservice.truestreamz.com",
#     "https://saregamapa.truestreamz.com",
#     "https://ntvdev.truestreamz.com",
#     "https://nitvsms.truestreamz.com",
#     "https://sptv.truestreamz.com",
#     "https://votingdev.truestreamz.com",
#     "https://epg.truestreamz.com",
#     "https://ntvedge.truestreamz.com",
#     "https://radionepaldev.truestreamz.com",
#     "https://mnm.truestreamz.com",
#     "https://nvoting.truestreamz.com",
#     "https://devmwstb1.truestreamz.com",
#     "https://support.truestreamz.com",
#     "https://bnpjwebsdk.truestreamz.com",
#     "https://bnpjdev.truestreamz.com",
#     "https://bnpjresume.truestreamz.com",
#     "https://nitvrecruit.truestreamz.com",
#     "https://radionepal.truestreamz.com",
#     "https://devwodapi.truestreamz.com",
#     "https://devwodiptv.truestreamz.com",
#     "https://wodapi.truestreamz.com",
#     "https://devtms.truestreamz.com",
#     "https://electionapi.truestreamz.com",
#     "https://dbilling.truestreamz.com",
#     "https://electadmin.truestreamz.com",
#     "https://mnmdev1.truestreamz.com",
#     "https://radionews.truestreamz.com",
#     "https://devapi.truestreamz.com",
#     "https://nplb.truestreamz.com",
#     "https://nplc.truestreamz.com",
#     "https://wtvgoapi.truestreamz.com",
#     "https://wtvgomicro.truestreamz.com",
#     "https://adnet.truestreamz.com",
#     "https://adtest.truestreamz.com",
#     "https://jenkins.truestreamz.com",
#     "https://emailservice.truestreamz.com",
#     "https://nitvcrmapi.truestreamz.com",
#     "https://nitvcrm.truestreamz.com",
#     "https://jnwalletdev.truestreamz.com",
#     "https://demo.truestreamz.com",
#     "https://dartsliveweb.truestreamz.com",
#     "https://dartsliveapi.truestreamz.com",
#     "https://dartsliveapi1.truestreamz.com",
#     "https://dartsliveweb1.truestreamz.com",
#     "https://dltvweb.truestreamz.com",
#     "https://dltvapi.truestreamz.com",
#     "https://mnsite.truestreamz.com",
#     "https://range2079.truestreamz.com",
#     "https://rangeadmin2079.truestreamz.com",
#     "https://ntvge2079.truestreamz.com",
#     "https://ntvgeapi2079.truestreamz.com",
#     "https://jp.truestreamz.com",
#     "https://mediaupload.truestreamz.com",
#     "https://dhdb1.truestreamz.com",
#     "https://jwplayertest.truestreamz.com",
#     "https://mnmedia.truestreamz.com",
#     "https://rpsremit.truestreamz.com",
#     "https://adnetwork.truestreamz.com",
#     "https://iptvota.truestreamz.com",
#     "https://nitvpm.truestreamz.com",
#     "https://devps.truestreamz.com",
#     "https://dartslogserver.truestreamz.com",
#     "https://jpedge3.truestreamz.com",
#     "https://nitvps.truestreamz.com",
#     "https://kaski2.truestreamz.com",
#     "https://devispapi.truestreamz.com",
#     "https://dhitv.truestreamz.com",
#     "https://dhvod.truestreamz.com",
#     "https://dhepg.truestreamz.com",
#     "https://kubemaster.truestreamz.com",
#     "https://kubenode1.truestreamz.com",
#     "https://kubenode2.truestreamz.com",
#     "https://dhapi1.truestreamz.com",
#     "https://dhlb.truestreamz.com",
#     "https://stgiptvapi.truestreamz.com",
#     "https://stgiptv.truestreamz.com",
#     "https://stgiptvvod.truestreamz.com",
#     "https://stgiptvmovies.truestreamz.com",
#     "https://stgiptvhoteltv.truestreamz.com",
#     "https://stgiptvmwstb.truestreamz.com",
#     "https://stgiptvwtg.truestreamz.com",
#     "https://stgiptvepg.truestreamz.com",
#     "https://stgrps.truestreamz.com",
#     "https://stgcrmapi.truestreamz.com",
#     "https://stgcrm.truestreamz.com",
#     "https://iptvwebui.truestreamz.com",
#     "https://stgrpsapi.truestreamz.com",
#     "https://rpsweb.truestreamz.com",
#     "https://wodk8api.truestreamz.com",
#     "https://iptvads.truestreamz.com",
#     "https://monitoring.truestreamz.com",
#     "https://lis.truestreamz.com",
#     "https://epg.truestreamz.com",
#     "https://sptvaws.truestreamz.com",
#     "https://sptvnp.truestreamz.com",
#     "https://demodashboard.truestreamz.com",
#     "https://iptvchecker.truestreamz.com",
#     "https://wodiptvdb.truestreamz.com",
#     "https://testbeta.truestreamz.com",
#     "https://rps.truestreamz.com",
#     "https://rpsapi.truestreamz.com",
#     "https://wodvod.truestreamz.com",
#     "https://iptvepg.truestreamz.com",
#     "https://minukapi.truestreamz.com",
#     "https://minukweb.truestreamz.com",
#     "https://radiotest.truestreamz.com",
#     "https://demoapi.truestreamz.com",
#     "https://demovod.truestreamz.com",
#     "https://whmcs.truestreamz.com",
#     "https://xtrem.truestreamz.com",
#     "https://dhapi2.truestreamz.com",
#     "https://nitv.truestreamz.com",
#     "https://mail-admin.newitventure.com",
#     "https://cloud3.newitventure.com",
#     "https://dev.newitventure.com",
#     "https://broadcasters.newitventure.com",
#     "https://hoteltv.newitventure.com",
#     "https://web2.newitventure.com",
#     "https://newbroad.newitventure.com",
#     "https://www.hoteltv.newitventure.com",
#     "https://smartpit.newitventure.com",
#     "https://crm.newitventure.com",
#     "https://invoice.newitventure.com",
#     "https://cloudnew.newitventure.com",
#     "https://hoteldemo.newitventure.com",
#     "https://demont.newitventure.com",
#     "https://epgmaster.newitventure.com",
#     "https://prabhutv.newitventure.com",
#     "https://dynamo.newitventure.com",
#     "https://tvshows.newitventure.com",
#     "https://vod.newitventure.com",
#     "https://drm.newitventure.com",
#     "https://demoind.newitventure.com",
#     "https://dev.crm.newitventure.com",
#     "https://otaprabhu.newitventure.com",
#     "https://billing.newitventure.com",
#     "https://ntv.newitventure.com",
#     "https://vpn.newitventure.com",
#     "https://mnm.newitventure.com",
#     "https://ntvtvshows.newitventure.com",
#     "https://devntv.newitventure.com",
#     "https://mnmnepal.newitventure.com",
#     "https://mnmserver.newitventure.com",
#     "https://ntcmomo.newitventure.com",
#     "https://support.newitventure.com",
#     "https://payment.newitventure.com",
#     "https://www.broadcasters.newitventure.com",
#     "https://www.newbroad.newitventure.com",
#     "https://wod.newitventure.com",
#     "https://sh.newitventure.com",
#     "https://wmspanel.newitventure.com",
#     "https://sparrow.newitventure.com",
#     "https://bank.newitventure.com",
#     "https://miraidev.newitventure.com",
#     "https://newitventure.com",
#     "https://www.newitventure.com",
#     "https://company.newitventure.com",
#     "https://nepalstar.newitventure.com",
#     "https://icando.newitventure.com",
#     "https://panel.newitventure.com",
#     "https://vbank.newitventure.com",
#     "https://sptv.newitventure.com",
#     "https://sptvtms.newitventure.com",
#     "https://ip.newitventure.com",
#     "https://mail.newitventure.com",
#     "https://ntvvoting.newitventure.com",
#     "https://recharge.newitventure.com",
#     "https://vpn2.newitventure.com",
#     "https://ntvtest.newitventure.com",
#     "https://tvshowstest.newitventure.com",
#     "https://mnmdev.nettvnepal.com.np",
#     "https://testapi.nettvnepal.com.np",
#     "https://test001.nettvnepal.com.np",
#     "https://apptest.nettvnepal.com.np",
#     "https://app.nettvnepal.com.np",
#     "https://mnmdev1.nettvnepal.com.np",
#     "https://coshipprabhu.nettvnepal.com.np",
#     "https://iptvservicedemo.nettvnepal.com.np",
#     "https://movieservicedemo.nettvnepal.com.np",
#     "https://tvshowsdemo.nettvnepal.com.np",
#     "https://iptvservice.nettvnepal.com.np",
#     "https://vianetdev.nettvnepal.com.np",
#     "https://jobapi.nettvnepal.com.np",
#     "https://nepaltv.nettvnepal.com.np",
#     "https://loadbalancer.nettvnepal.com.np",
#     "https://momoapi.nettvnepal.com.np",
#     "https://news.nettvnepal.com.np",
#     "https://mnm.nettvnepal.com.np",
#     "https://wodiptv.nettvnepal.com.np",
#     "https://wodmovies.nettvnepal.com.np",
#     "https://wodtvshows.nettvnepal.com.np",
#     "https://devcrm.nettvnepal.com.np",
#     "https://jp.nettvnepal.com.np",
#     "https://nettvnepal.com.np",
#     "https://ntv.livetv.nettvnepal.com.np",
#     "https://mirai.nettvnepal.com.np",
#     "https://insurance.nettvnepal.com.np",
#     "https://ntvnews.nettvnepal.com.np",
#     "https://ird.nettvnepal.com.np",
#     "https://tvtoday.nettvnepal.com.np",
#     "https://geetlog.nettvnepal.com.np",
#     "https://papasbal.nettvnepal.com.np",
#     "https://livetoday.nettvnepal.com.np",
#     "https://ntcmomo.nettvnepal.com.np"
# ]

# # Function to check URL status
# def check_url_status(url):
#     try:
#         response = requests.head(url, timeout=10)
#         status_code = response.status_code
#         if status_code == 200:
#             return "Accessible"
#         else:
#             return f"Not Accessible (Status Code: {status_code})"
#     except requests.ConnectionError:
#         return "Error: Connection Error"
#     except requests.Timeout:
#         return "Error: Timeout Error"
#     except requests.RequestException as e:
#         return f"Error: {str(e)}"

# # Iterate through each URL and print status
# for idx, url in enumerate(urls, start=1):
#     status = check_url_status(url)
#     print(f"{idx}\t{url}\t{status}")

from flask import Flask, render_template # type: ignore
import requests

app = Flask(__name__)

# Replace with your list of URLs
urls = [
    "https://cloud.truestreamz.com",
    "https://default.truestreamz.com",
    "https://eu.truestreamz.com",
    "https://ca.truestreamz.com",
    "https://in.truestreamz.com",
    "https://sf.truestreamz.com",
    "https://np.truestreamz.com",
    "https://dvr.truestreamz.com",
    "https://momo.truestreamz.com",
    "https://mnmott.truestreamz.com",
    "https://nepaltv.truestreamz.com",
    "https://petmarketing.truestreamz.com",
    "https://devbroadcasters.truestreamz.com",
    "https://mnmstg.truestreamz.com",
    "https://nspdev.truestreamz.com",
    "https://nspresume.truestreamz.com",
    "https://deviptv.truestreamz.com",
    "https://devmovies.truestreamz.com",
    "https://devmicromovies.truestreamz.com",
    "https://devtvshows.truestreamz.com",
    "https://devepg.truestreamz.com",
    "https://wodiptv.truestreamz.com",
    "https://wodmovies.truestreamz.com",
    "https://wodmicromovies.truestreamz.com",
    "https://wodmwstb.truestreamz.com",
    "https://jobterrace.truestreamz.com",
    "https://nspweb.truestreamz.com",
    "https://tms.truestreamz.com",
    "https://devmwstb.truestreamz.com",
    "https://wodtvshows.truestreamz.com",
    "https://demoiptv.truestreamz.com",
    "https://demomovies.truestreamz.com",
    "https://demomicromovies.truestreamz.com",
    "https://demotvshows.truestreamz.com",
    "https://demomwstb.truestreamz.com",
    "https://demohotelservice.truestreamz.com",
    "https://saregamapa.truestreamz.com",
    "https://ntvdev.truestreamz.com",
    "https://nitvsms.truestreamz.com",
    "https://sptv.truestreamz.com",
    "https://votingdev.truestreamz.com",
    "https://epg.truestreamz.com",
    "https://ntvedge.truestreamz.com",
    "https://radionepaldev.truestreamz.com",
    "https://mnm.truestreamz.com",
    "https://nvoting.truestreamz.com",
    "https://devmwstb1.truestreamz.com",
    "https://support.truestreamz.com",
    "https://bnpjwebsdk.truestreamz.com",
    "https://bnpjdev.truestreamz.com",
    "https://bnpjresume.truestreamz.com",
    "https://nitvrecruit.truestreamz.com",
    "https://radionepal.truestreamz.com",
    "https://devwodapi.truestreamz.com",
    "https://devwodiptv.truestreamz.com",
    "https://wodapi.truestreamz.com",
    "https://devtms.truestreamz.com",
    "https://electionapi.truestreamz.com",
    "https://dbilling.truestreamz.com",
    "https://electadmin.truestreamz.com",
    "https://mnmdev1.truestreamz.com",
    "https://radionews.truestreamz.com",
    "https://devapi.truestreamz.com",
    "https://nplb.truestreamz.com",
    "https://nplc.truestreamz.com",
    "https://wtvgoapi.truestreamz.com",
    "https://wtvgomicro.truestreamz.com",
    "https://adnet.truestreamz.com",
    "https://adtest.truestreamz.com",
    "https://jenkins.truestreamz.com",
    "https://emailservice.truestreamz.com",
    "https://nitvcrmapi.truestreamz.com",
    "https://nitvcrm.truestreamz.com",
    "https://jnwalletdev.truestreamz.com",
    "https://demo.truestreamz.com",
    "https://dartsliveweb.truestreamz.com",
    "https://dartsliveapi.truestreamz.com",
    "https://dartsliveapi1.truestreamz.com",
    "https://dartsliveweb1.truestreamz.com",
    "https://dltvweb.truestreamz.com",
    "https://dltvapi.truestreamz.com",
    "https://mnsite.truestreamz.com",
    "https://range2079.truestreamz.com",
    "https://rangeadmin2079.truestreamz.com",
    "https://ntvge2079.truestreamz.com",
    "https://ntvgeapi2079.truestreamz.com",
    "https://jp.truestreamz.com",
    "https://mediaupload.truestreamz.com",
    "https://dhdb1.truestreamz.com",
    "https://jwplayertest.truestreamz.com",
    "https://mnmedia.truestreamz.com",
    "https://rpsremit.truestreamz.com",
    "https://adnetwork.truestreamz.com",
    "https://iptvota.truestreamz.com",
    "https://nitvpm.truestreamz.com",
    "https://devps.truestreamz.com",
    "https://dartslogserver.truestreamz.com",
    "https://jpedge3.truestreamz.com",
    "https://nitvps.truestreamz.com",
    "https://kaski2.truestreamz.com",
    "https://devispapi.truestreamz.com",
    "https://dhitv.truestreamz.com",
    "https://dhvod.truestreamz.com",
    "https://dhepg.truestreamz.com",
    "https://kubemaster.truestreamz.com",
    "https://kubenode1.truestreamz.com",
    "https://kubenode2.truestreamz.com",
    "https://dhapi1.truestreamz.com",
    "https://dhlb.truestreamz.com",
    "https://stgiptvapi.truestreamz.com",
    "https://stgiptv.truestreamz.com",
    "https://stgiptvvod.truestreamz.com",
    "https://stgiptvmovies.truestreamz.com",
    "https://stgiptvhoteltv.truestreamz.com",
    "https://stgiptvmwstb.truestreamz.com",
    "https://stgiptvwtg.truestreamz.com",
    "https://stgiptvepg.truestreamz.com",
    "https://stgrps.truestreamz.com",
    "https://stgcrmapi.truestreamz.com",
    "https://stgcrm.truestreamz.com",
    "https://iptvwebui.truestreamz.com",
    "https://stgrpsapi.truestreamz.com",
    "https://rpsweb.truestreamz.com",
    "https://wodk8api.truestreamz.com",
    "https://iptvads.truestreamz.com",
    "https://monitoring.truestreamz.com",
    "https://lis.truestreamz.com",
    "https://epg.truestreamz.com",
    "https://sptvaws.truestreamz.com",
    "https://sptvnp.truestreamz.com",
    "https://demodashboard.truestreamz.com",
    "https://iptvchecker.truestreamz.com",
    "https://wodiptvdb.truestreamz.com",
    "https://testbeta.truestreamz.com",
    "https://rps.truestreamz.com",
    "https://rpsapi.truestreamz.com",
    "https://wodvod.truestreamz.com",
    "https://iptvepg.truestreamz.com",
    "https://minukapi.truestreamz.com",
    "https://minukweb.truestreamz.com",
    "https://radiotest.truestreamz.com",
    "https://demoapi.truestreamz.com",
    "https://demovod.truestreamz.com",
    "https://whmcs.truestreamz.com",
    "https://xtrem.truestreamz.com",
    "https://dhapi2.truestreamz.com",
    "https://nitv.truestreamz.com",
    "https://mail-admin.newitventure.com",
    "https://cloud3.newitventure.com",
    "https://dev.newitventure.com",
    "https://broadcasters.newitventure.com",
    "https://hoteltv.newitventure.com",
    "https://web2.newitventure.com",
    "https://newbroad.newitventure.com",
    "https://www.hoteltv.newitventure.com",
    "https://smartpit.newitventure.com",
    "https://crm.newitventure.com",
    "https://invoice.newitventure.com",
    "https://cloudnew.newitventure.com",
    "https://hoteldemo.newitventure.com",
    "https://demont.newitventure.com",
    "https://epgmaster.newitventure.com",
    "https://prabhutv.newitventure.com",
    "https://dynamo.newitventure.com",
    "https://tvshows.newitventure.com",
    "https://vod.newitventure.com",
    "https://drm.newitventure.com",
    "https://demoind.newitventure.com",
    "https://dev.crm.newitventure.com",
    "https://otaprabhu.newitventure.com",
    "https://billing.newitventure.com",
    "https://ntv.newitventure.com",
    "https://vpn.newitventure.com",
    "https://mnm.newitventure.com",
    "https://ntvtvshows.newitventure.com",
    "https://devntv.newitventure.com",
    "https://mnmnepal.newitventure.com",
    "https://mnmserver.newitventure.com",
    "https://ntcmomo.newitventure.com",
    "https://support.newitventure.com",
    "https://payment.newitventure.com",
    "https://www.broadcasters.newitventure.com",
    "https://www.newbroad.newitventure.com",
    "https://wod.newitventure.com",
    "https://sh.newitventure.com",
    "https://wmspanel.newitventure.com",
    "https://sparrow.newitventure.com",
    "https://bank.newitventure.com",
    "https://miraidev.newitventure.com",
    "https://newitventure.com",
    "https://www.newitventure.com",
    "https://company.newitventure.com",
    "https://nepalstar.newitventure.com",
    "https://icando.newitventure.com",
    "https://panel.newitventure.com",
    "https://vbank.newitventure.com",
    "https://sptv.newitventure.com",
    "https://sptvtms.newitventure.com",
    "https://ip.newitventure.com",
    "https://mail.newitventure.com",
    "https://ntvvoting.newitventure.com",
    "https://recharge.newitventure.com",
    "https://vpn2.newitventure.com",
    "https://ntvtest.newitventure.com",
    "https://tvshowstest.newitventure.com",
    "https://mnmdev.nettvnepal.com.np",
    "https://testapi.nettvnepal.com.np",
    "https://test001.nettvnepal.com.np",
    "https://apptest.nettvnepal.com.np",
    "https://app.nettvnepal.com.np",
    "https://mnmdev1.nettvnepal.com.np",
    "https://coshipprabhu.nettvnepal.com.np",
    "https://iptvservicedemo.nettvnepal.com.np",
    "https://movieservicedemo.nettvnepal.com.np",
    "https://tvshowsdemo.nettvnepal.com.np",
    "https://iptvservice.nettvnepal.com.np",
    "https://vianetdev.nettvnepal.com.np",
    "https://jobapi.nettvnepal.com.np",
    "https://nepaltv.nettvnepal.com.np",
    "https://loadbalancer.nettvnepal.com.np",
    "https://momoapi.nettvnepal.com.np",
    "https://news.nettvnepal.com.np",
    "https://mnm.nettvnepal.com.np",
    "https://wodiptv.nettvnepal.com.np",
    "https://wodmovies.nettvnepal.com.np",
    "https://wodtvshows.nettvnepal.com.np",
    "https://devcrm.nettvnepal.com.np",
    "https://jp.nettvnepal.com.np",
    "https://nettvnepal.com.np",
    "https://ntv.livetv.nettvnepal.com.np",
    "https://mirai.nettvnepal.com.np",
    "https://insurance.nettvnepal.com.np",
    "https://ntvnews.nettvnepal.com.np",
    "https://ird.nettvnepal.com.np",
    "https://tvtoday.nettvnepal.com.np",
    "https://geetlog.nettvnepal.com.np",
    "https://papasbal.nettvnepal.com.np",
    "https://livetoday.nettvnepal.com.np",
    "https://ntcmomo.nettvnepal.com.np"
]

def check_status(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return "Accessible"
        else:
            return f"Error: {response.status_code}"
    except requests.RequestException as e:
        return f"Error: {e}"

@app.route('/')
def dashboard():
    statuses = {url: check_status(url) for url in urls}
    return render_template('dashboard.html', statuses=statuses)

if __name__ == '__main__':
    app.run(debug=True)
